RUN apt-get update && apt-get upgrade -y \
  && apt-get install -y curl wget git \
	&& apt-get clean \
	&& rm -fr /var/lib/apt/lists/*

RUN curl -sfL https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz | tar xvzf -C / -
